### ISSUE TITLE
Select branch or commit to deploy

### ISSUE THREAD

**Issue by pascalfree** [juntagrico/juntagrico-paas#2]
This would be helpful to easily move back to a previous version, when one has problems with an update and can't fix it quickly.

Probably somewhere here this would go.
https://github.com/juntagrico/juntagrico-paas/blob/da88b877b8ee8958019594e3048816976020afb0/adminconsole/management/commands/rebuild_docker.py#L26

**Comment by patrickuhlmann** [comment]
Recently I had a problem because of a merge conflict. The working directory was then in an unclean state.

Maybe you could also add a button to run "git reset -- hard" to "clean" the working directory.
